### ISSUE TITLE
Mount external volumes

### ISSUE THREAD

**Issue by joshnat** [tom472/mediabox#22]
I'm new to Docker, and was able to install Mediabox with no problem on a fresh Ubuntu 17.10 install.  Previously I was running all my media apps individually, but wanted deluge/vpn and split tunneling wasn't working for me.  I also liked the ease of install of Mediabox and your readme was perfect.

All my media is saved on a separate volume from the host, but the same computer.  The mountpoint is /media/josh/AUDIOVISUAL, with sub directories for movies, shows, music, etc. 

How can I configure the Sonarr, Couchpotato, Radarr, etc containers in Mediabox to move downloaded media from Deluge to this volume, and how can I configure the Plex container to pull the media from there?  I've poked around Portainer and can't see how to do it.  

Thanks!

**Comment by joshnat** [comment]
Nevermind, I think I figured it out.  I needed to edit the container in Portainer, and change the paths from the paths inside the mediabox folder to the mounted volumes on the host.  Phew!  If you have any other insight please let me know!

**Comment by tom472** [comment]
FYI - The locations that the Mediabox project ~are~ mount point on the "host" machine they however are located under where you downloaded the repo to.

One of the items that I am working on is a way to have the user provide folders/locations during the setup if they already have directories with data in them already.

Is your `/media/josh/AUDIOVISUAL` location on a different disk from where the Mediabox containers are running?
If that is not a different disk then the easiest way would just be to move the data from your original locations to the corresponding Mediabox locations.

However if this is a different disk and you have it that way because it is a larger disk then it's a little harder, but we can probably get it worked out for you.

Let me know a bit more about your config and we can go from there.

--Tom

**Comment by tom472** [comment]
Closing this issue - @joshnat if you come back and need more help just let me know.
