### ISSUE TITLE
Add Mylar support

### ISSUE THREAD

**Issue by rudolph4404** [tom472/mediabox#29]
Add Mylar support for comics and lidarr for ebooks.

**Comment by kspillane** [comment]
I can take care of this over the next week.  

Would probably also want to add Gazee for reading comics, and may as well add Headphones for music.  

Thoughts on this @tom472 ?

**Comment by tom472** [comment]
Headphones has been on the "ToDo" for a while -- 
But I am currently really trying to fix/improve the landing page.
So these requests might need to wait just a bit.

I have been testing [Organizr](https://organizr.us/) and pretty much have a working config.
Testing this weekend should let me know if I can get the custom config shimmed in to the project.

But in general - Yes - Headphones, Mylar, Lidarr, and Gazee are all highly probable to be added.

@rudolph4404 - Thanks for the requests
@kspillane - Give me just a little bit more time to finish the landing page stuff then I think we will have a nice jumping off point for adding any additional containers.

Thanks

**Comment by kspillane** [comment]
Hey @tom472 any update on the Organizr front-end front?  

I tried it out, it was ok. Have you looked into [Muximux](https://github.com/mescon/Muximux)?

**Comment by tom472** [comment]
Sorry just seeing this been away on vacation. 
I've tried muximux and organizr kinda liked organizr better. Does muximux still need a plug-in for it to work correctly in some browsers? That was a stopping point for using that for me.
I do have a pretty good working setup that I need to add in and commit. I should be able to get to that pretty soon after I return from vacation.

**Comment by tom472** [comment]
Hey @kspillane 
So it turns out Organizr's config is tough to adjust on the fly with current settings etc.
Gave it a couple tests but really couldn't get to to be "easy".
I'll be looking a Muximux again soon - probably over this weekend.
Stay tuned .. 
Have you done / tested any configs with Muximux yet?

**Comment by kspillane** [comment]
Nope, I just installed it to see what it was all about and realized it looked a lot simpler than organizr.  

If Muximux is going to be a problem, I can retool [PyRedirector](https://github.com/kspillane/pyredirector) (my python / flask URL redirector) to suit our needs. I have been meaning to add an REST API so you can add redirects programmatically. I can easily change its functionality to only handle the URL redirects we want. Should be easy to whip up a basic front-end (I hate doing UI design though).  

Upon reflection, this may be the most flexible solution, plus it gives me a reason to go back and work on it since I have been lazy. If you want to play with Muximux that's cool, but I will try to get a working container for you by the beginning of next week and we can see what you think!

**Comment by tom472** [comment]
If you could "containerize" your tool and it can be easily manipulated via the commandline/mediabox script that would be pretty cool.

I TOTALLY feel you on the "(I hate doing UI design though)." I am exactly the same. (As is totally apparent for the current horrible landing page)

I am definitely going to effort on Muximux over the weekend because it's a pretty simple container and shouldn't take to long test/try.

Thanks again for all the ideas and help!

**Comment by tom472** [comment]
Not really enough want for this - closing for now.
