### ISSUE TITLE
help with drives

### ISSUE THREAD

**Issue by erfly7** [tom472/mediabox#30]
Need help with drive permissions none of programs see hard drives

**Comment by kspillane** [comment]
Hey @erfly7 !  

I am going to be away from my pc most of today, but I can try to help.  

First, what distribution and version of Linux are you using?  
What release of docker and docker-compose are you running?
Can you do ls -l in the directory you are running mediabox from, so we can see the current permissions and ownerships?  

Can you be a little more specific about the issue? Do the programs run and are you able to access their interfaces? Can you give a specific example of what you are trying to do when the problem happens? Like trying to add a library in Plex or a directory in Sonarr? Does the directory show up in those programs and then you get a permissions error?  

Thanks!

**Comment by erfly7** [comment]
Ubuntu MATE 16.04

just copied the instructions from the page so not sure what docker versions?

Not sure what meant by directory running mediabox from?  (I did uninstall Mediabox and wiped my hard drives and reinstalled Ubuntu 16.04 , because could not find drives so if there is a solution would have to reinstall mediabox)

The issue is Mediabox installed fine and got to that page with all the programs Plex, sonarr, etc with the ip addresses listed next to them,  when I clicked on them it took me to the web gui of each program, however especially in PLEX the most important when I went to add a movie library none of my 5 internal HDD were listed, some are empty and new but two are old and contain 4TB of movies to be the PLEX library, all the drives are mounted mnt/Media1, mnt/Media2 etc.   None would show up in the PLEX app started through the mediabox page.

Also the SSD drive which Ubuntu and Mediabox are installed is only 120GB so I don't want Deluge or Sonarr or Radarr etc to download anything to that drive.

So the programs run and I can access their interfaces but it seems none of them show my mounted hard drives where I need Movies etc to be downloaded too and stored for Plex

I assumed it was a permissions error since in previous installs of Plex and Sonarr they would not show my drives until I chmod, and chown various ways until they somehow started showing up

**Comment by kspillane** [comment]
Ok, so the problem here is not a mediabox or a permissions issue. It is sounds like you are unclear how docker handles mount points for drive mappings.  

Basically, when something runs in Docker, it runs isolated from the rest of your operating system, and that includes being able to access your hard drives. In general mediabox makes a directory called content (I think, I will admit, I don't actually use mediabox, because I have a rather complex setup). That content directory is mapped in the docker-compose file to the data mounts for Plex and the other containers.  

Bacially, the issue here is mediabox is not as flexible as you need. The simplest fix would be to make a symbolic link of the content directory (or if you have multiple drives, put the links inside the content directory), or edit the docker-compose file to add additional mounts.

You can do man ln to learn how to make symbolic links and the docker compose documentation at their website explains how to do mounts.  

I will be available later if you want some more detailed help.  

Thanks!

**Comment by erfly7** [comment]
Thanks so much for the reply

Yeah that's disappointing.

never used Docker before so completely lost as how to do this?

read some of the mounting volumes in Docker is beyond my Linux skill level.

any help or example you could offer would be great.

**Comment by tom472** [comment]
@erfly7 We can probably get this configured with a little tweaking.
Fist thing I would need to know is do you have all of the drives mounted under one location like `/mnt` on your Ubuntu system?

Medaibox right now is kind of set-up for people starting up a stack "for the first time".
I know that this is not optimal and that there are people that will want to use Mediabox who already have media/content on their systems.

Adjustting for that is going to be added to the install script fairly soon, but doesn't mean we can't get something working for you now.

Can you let me know if all your disks are mounted off a single location and if they are can you give me a `dir` of that location?

**Comment by erfly7** [comment]
Away from the PC until tonight but as couldn't get it working thought it was something on my end I wiped ubuntu and mediabox and just did clean install of ubuntu and that is as far as I have gotten as been looking around at alternatives like OMV, unraid etc.

but computer has unbuntu 16.04 installed on 120GB SSD

then 5 HDD that

/mnt/Media1

/mnt/Media2 <--------has movies/tv

/mnt/Media3 <--------has movies/tv

/mnt/Media4

/mnt/Media5

all the rest are just blank right now except for the two noted

**Comment by tom472** [comment]
Sorry I meant an "ls" of the location not "dir". (Windows / Linux brain mixup for a minute).
But what you provided above is basically what I was looking for.

Let me work on this a bit but I should be able to come up with a fix/tweak to get this going for you.

**Comment by erfly7** [comment]
Thanks I have not messed around with permissions or ownership of the drives yet as i know that always gave me problems with PLEX seeing them.

Also always had problems with Deluge, transmission etc downloading to a Download folder and then Sonarr and Radarr moving that completed file to storage on another hard drive.

**Comment by kspillane** [comment]
Without giving a discourse on how to do storage with docker, here is the simplest thing you can do to fix your issues.  

In the docker-compose file, there are sections for each service called volume. Here is the excerpt from the compose file for the section on plex:

~~~~
          volumes:
            - './plex:/config'
            - './plex/transcode:/transcode'
            - './content/tv:/data/tvshows'
            - './content/movies:/data/movies'
            - '/etc/localtime:/etc/localtime:ro'
~~~~

The syntax works like this, `- '/path/to/actual/directory/on/machine:/mapped/path/in/container'`  
So, if you have a path called `/home/user/mediabox/stuff` and you wanted its contents to be available inside a docker container as, say, `/stuff` you'd add `- '/home/user/mediabox/stuff:/stuff'` to the volume section of the compose file. It needs to be lined up with the other volume lines, because indenting is part of the formatting for compose files. Don't use tab, just use space.  

So, if you added `- '/mnt/media:/data1'` to the plex volumes section, and the restarted the stack `docker-compose down || docker-compose up -d`. The contents of /mnt/media will show up in /data inside plex. So you could add it as a library, or the like. Rinse and repeat with your other drives, just give them unique names in each container, like /data2, /data3, etc. As long as the user who ran the mediabox installer has permissions to read (or write depending on what you are doing) you should be fine. Can also be used to setup download directories for use between downloaders and managers. Just change the apparopriate paths in the other services. You'll want to save that info, because it will be overwritten if you rerun the script again.  

As an example, here is my plex configuration (remember, I don't actually use mediabox to manage my stack, but I think it is great and that's why I like helping):  
~~~~
    volumes:
      - /pool2/containers/plex:/config
      - /nas2/transcode:/transcode
      - /nas/media:/data
      - /nas2/media:/data2
~~~~

In my case /nas is a 10TB SATA drive that contains my TV shows, and /nas2 is a ZFS striped array (3TB = 9TB) that hold everything else. /pool2 is a mirrored ZFS array that contains all my containers' configuration files.  

If you are feeling adventurous, [click here](https://docs.docker.com/storage/bind-mounts/#use-a-read-only-bind-mount) docker documentation on it.  

Let us know if that helps you out, or if you have any other questions. Like @tom472 said, look for more ease of use and customizability in the future.  

Thanks!

**Comment by erfly7** [comment]
Yeah thanks that is pretty clear aside from is there a compose file for each container (Plex, Sonarr etc?)

and how do you access it?

**Comment by tom472** [comment]
There is one compose file it is located in the `mediabox` folder.
Named `docker-compose.yml`.

**Comment by dp917** [comment]
Easiest thing is to edit volumes in Portainer. I was having same issue but was able to go into each container and change tv and movie folders to my storage pool of hdd's and so far seems to be working

**Comment by tom472** [comment]
@dp917 Thanks for jumping in and mentioning this.
You're totally right - the easiest way to handle it is to adjust it in Portainer.

@erfly7 Basically all you would need to do is go to Portainer - Stop any of the containers you need to adjust - then use the "Duplicate/Edit" button and make the adjustments you need.
Under the "Advanced container settings" you can easily change the mappings you need to the appropriate locations on your host PC.
