### ISSUE TITLE
How to best to enable nzbget with vpn support

### ISSUE THREAD

**Issue by depasseg** [tom472/mediabox#39]
Do you see an issue with changing out the nzbget section of docker-compose with this container and options, to take advantage of the vpn capability?  Or to put it another way, what's the best way to add vpn support to nzbget (like there is for deluge)?

https://github.com/jshridha/docker-nzbgetvpn

**Comment by rudolph4404** [comment]
I thought that the way the deluge docker was set up allowed for other things to be routed through the vpn.-ChuckOn Apr 20, 2018 7:18 PM, depasseg <notifications@github.com> wrote:Do you see an issue with changing out the nzbget section of docker-compose with this container and options, to take advantage of the vpn capability?  Or to put it another way, what's the best way to add vpn support to nzbget (like there is for deluge)?
https://github.com/jshridha/docker-nzbgetvpn

**Comment by rudolph4404** [comment]
https://github.com/dperson/openvpn-client/blob/master/README.md-ChuckOn Apr 21, 2018 10:20 AM, depasseg <notifications@github.com> wrote:I'm not seeing that.  curl ifconfig.co on the delugevpn console shows my vpn address.  the same on my nzbget console shows my local wan ip.

**Comment by depasseg** [comment]
I like the idea of having an openvpn container and then having containers (like deluge and nzbget) use that as it's network, but I fear it's over my head to configure.

**Comment by rudolph4404** [comment]
If I remember correctly, delugevpn has openvpn in it. It should just be a matter of pointing the nzbget container to the delugevpn container for its networking. See the URL I sent earlier for details.Disclaimer: I have not tried this myself.-ChuckOn Apr 21, 2018 11:33 AM, depasseg <notifications@github.com> wrote:I like the idea of having an openvpn container and then having containers (like deluge and nzbget) use that as it's network, but I fear it's over my head to configure.

**Comment by depasseg** [comment]
I was able to modify the docker-compose.yml file to use the docker image that included the PIA VPN capability that I listed above.  I had one issue afterward (errors about certificate checking failed), which resolved once I changed the nzbget Settings -> Paths -> CertStore option to be /etc/ssl/certs/ca-certificates.crt

    # ----------------------------------------
    # NZBGet
    # ----------------------------------------
    nzbget:
        image: jshridha/docker-nzbgetvpn:latest
        container_name: nzbget
        restart: unless-stopped
        cap_add:
            - NET_ADMIN
        environment:
          - PUID=${PUID}
          - PGID=${PGID}
          - VPN_ENABLED=yes
          - VPN_USER=${PIAUNAME}
          - VPN_PASS=${PIAPASS}
          - VPN_REMOTE=${VPN_REMOTE}
          - VPN_PORT=1198
          - VPN_PROTOCOL=udp
          - VPN_DEVICE_TYPE=tun
          - VPN_PROV=pia
          - STRONG_CERTS=no 
          - ENABLE_PRIVOXY=yes
          - STRICT_PORT_FORWARD=yes
          - LAN_NETWORK=${CIDR_ADDRESS}
          - NAME_SERVERS=1.1.1.1,1.0.0.1 
          - DEBUG=false
        network_mode: 'bridge'  
        ports:
          - '${IP_ADDRESS}:6789:6789'
        volumes:
          - './content:/data'
          - './nzbget:/config'
          - './content/completed:/downloads'
          - '/etc/localtime:/etc/localtime:ro'

**Comment by tom472** [comment]
@depasseg  I'm not really following you - probably because I don't use nzbget.

Is nzbget not able to use the deluge container as its download client?
If you use the Deluge container as your download client for any other applications, they all will have VPN protection.

Does nzbget have it's own internal download client/mechanism? 
(Which then for sure would want its own VPN protection.)
As I said I don't use it so I am unfamiliar with it.

**Comment by depasseg** [comment]
nzbget is identical in functionality to deluge at a high level.  Both download stuff.  Deluge uses p2p and nzbget uses nntp.

nzbget doesn't use the deluge vpn since it's downloading directly.  hence using an image that includes vpn (just like deluge).

Alternatively, we could setup an openvpn container, and have deluge and nzbget (and whatever), use that as it's networking connection, but that would require an nginx container which would point to each internal management url.   I think this would really be a great way to go in the long run, since we could then enable https and letsencrypt in this container and have a secure frontend to everything.

**Comment by tom472** [comment]
@depasseg Yeah so I just started checking it out - and now I see that it is "also a downloader".

So if you have had relative success already with the container you linked I should be able to make that change.

When you say you fixed the error you were seeing by adjusting:
`nzbget Settings -> Paths -> CertStore option to be /etc/ssl/certs/ca-certificates.crt`
Do you mean you changed that via the nbzget web interface after the container was up?

**Comment by depasseg** [comment]
Hi - Yes, via the web interface.  I'm not sure where the setting came from, but it was ${AppDir}/cacert.pem

from what @rudolph4404 provided above, an openvpn container can provide vpn access to other containers pretty easily.  We just need to figure out the nginx piece.  I'd love to help out.

It seems like when I run the mediabox.sh script, it asks for all my saved settings again.  Anyway to have it use whatever existing settings there might be (especially the vpn UN and PW)?  It would make it a whole lot easier to do testing.

**Comment by depasseg** [comment]
Oh and if you are looking at redoing the web frontend stuff, consider organizr.  looks like it is much more versatile as a web frontend than muximux.

**Comment by tom472** [comment]
The mediabox.sh script does save "some" settings but not all and here is the thing about the VPN UN and PW - I can have it re-use them but then it will always re-use i.e. If you change or want to change your PIA UN and PW then this will still hold the old.
I guess I could prompt something like "We have a PIA UN & PW .. re-use them or provide new creds... blah blah" something like that.

About a VPN container itself while probably useful - there really shouldn't be anything else than the downloaders then need it.

I already tried Organizr and while nice and cool looking - all the setting are stored in a sqlite db and it was way to hard to "shove in" the settings of the current users environment.

BTW - thanks for trying the project and the info and suggestions - very appreciated.

**Comment by tom472** [comment]
Hey @depasseg Thank You for the Donation! 
Very Much Appreciated!
Thanks for supporting Mediabox!

**Comment by kspillane** [comment]
Hey all!  

I have been pretty overloaded at work recently and haven't had time to be active here, not sure when it will let up. Anyway, thought I would chime in here. As a very heavy NZBGet user, let me ask, do you really need VPN support?  

In a P2P environment (like bittorrent) you'll definitely want it since you are sharing files directly with others and they can get your IP. Plus, sketchy ISPs can monitor for bit torrent traffic and throttle or block it. But those same ISPs can also scan for and block or throttle common VPN traffic as it uses UDP port 1198. Myself, and most of my friends who use news for getting files simply use our new servers' encrypted NNTP ports that run on port 443. To our ISPs it just looks like we are surfing https and they don't care about that (unless you have bandwidth limits, but I digress). As far as server side goes, you are not likely to get a DMCA nastygram for using news. The news provider will get a take-down notice and pull the file.  

I am all for extra security, but it seems overly paranoid to use VPN on top of news. Plus, the overhead will impact the news server's throughput.

**Comment by depasseg** [comment]
My preference is to encrypt the entire session (below the HTTPS level).  ISPs are data mining and there is no need to give them any info.  So, yes, even if an nntp provider offers https/TLS I'd still like to be able to vpn.  The NABget part is pretty simple.  I can create (or try to at least) a pull request.

I think the more difficult, but more important piece, would be the central container to handle networking/nginx/let's encrypt etc.

**Comment by kspillane** [comment]
Well, if I were doing a central VPN encryption. I'd set up an openvpn client container as a gateway and then configure the other containers to use it as their default gateway. That way all the traffic gets passed through the VPN. You wouldn't even need to use the specialized VPN-enabled services, you'd just pass all traffic through a VPN container gateway.  

I used to run openvpn on an RPi and if I wanted traffic to be encrypted, I would just point the host to use the RPi as a default gateway, and then have the gateway pass all traffic into the tunnel.  

Probably really easy to do. I will look into it if I get some time.

**Comment by kspillane** [comment]
@depasseg I am curious, do you currently use NZBGet with VPN? I have a PIA account but I almost never use it because I just use usenet for all my things. When I tested with PIA in the past my speeds were pretty awful ~5Mbps down, without VPN NZBGet easily saturates my DSL (~44Mbps) even with SSL enabled.  

What info are you worried about them mining? With the SSL all they will see is you have a session with a remote IP that happens to be your usenet provider. If you have a VPN they will just see you sending traffic to a remote IP that is your VPN provider. Either way, unless your ISP is injecting root certs, in both cases they wont be able to see what files you are accessing. AFAIK encrypted usenet is just NNTP passed through an SSL proxy.  

I am all for options, but I think for most people a default setup of usenet over VPN would be overkill and would probably end up turning them off of usenet because of the speed loss.  

Perhaps we could fork off a tin-foil hat variant of mediabox (for running on seedboxes) where everything is pumped through a VPN and has certs and what not. I don't even use the SSL web interfaces for the various servers because I only access my media stack from inside my network.

**Comment by tom472** [comment]
@kspillane Thanks again for jumping in and providing additional info.
I love the "tin-foil hat" Mediabox idea and was actually thinking of the same thing, that idea might be something on the horizon as a fork.

I do the same as you - I'm only running the normal http interfaces for the containers because I only access them from home OR if remote I VPN in to home and access them.

**Comment by depasseg** [comment]
When I tested it I got 300mbps d/l over vpn to PIA. and that was running TLS to the nntp server on top of the vpn. 

implying that HTTPS negates the need for a vpn is a bit of a stretch.  DNS requests as well as the actual https server identity are easy to identify.  And it's easy to see it's going to and coming from that one host.  By using a vpn, this info is obfuscated and makes it hard to determine the actual endpoint (all they would see is a bunch of vpn traffic going to a vpn provider).

Feel free to not use a VPN, but I will.  And I suggest the readme be changed to reflect that the nzbget container as configured can't use vpn, because it's misleading.  And that was the point of this issue.

**Comment by depasseg** [comment]
It's all good.  :-)

My bad.  I'm sorry.  It wasn't in the readme.  I'm not sure where I got that idea, but it was the first reply to this issue.  Maybe that reinforced the idea.

**Comment by tom472** [comment]
closing this issue until the overall "tin-foil hat" version of Mediabox is created.

For the most part VPN is overkill for usenet - but I will look into creating a version of Medibox that uses the VPN throughout the entire project and then this will be covered.
