### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by element465** [tom472/mediabox#42]
Just installed, and every time I go to my IP where the server is, I get a 502 Bad Gateway.

Is there anything in Nginx that I need to do to get it working or is it a fairly turn-key solution?

Is there anything I need to do specially? Fairly new to this stuff, and always have issues like this with Ngnix.

I am getting this error for Muximux:
`[07-May-2018 23:56:26] ERROR: [pool www] please specify user and group other than root
[07-May-2018 23:56:26] ERROR: FPM initialization failed`

**Comment by tom472** [comment]
Is Muximux the only container having issues?

i.e. Can you hit Portainer? via http://IP-Address:9000
And see if all the containers are up and running?

Are you running any other firewalls etc. on the server?
Is something else using port 80?

This is (should) be totally turn-key and shouldn't need anything adjusted to "work right out of the box".

**Comment by element465** [comment]
Yes, I can access Portainer and they are all online.

I have installed it on a fresh 16.04 Ubuntu Server install, could it perhaps be that I ran the 

> ./mediabox.sh

as a

**Comment by tom472** [comment]
No you should not run the mediabox.sh script as sudo.

It should be run as/under your user account.

**Comment by element465** [comment]
That's probably something to do with it then!

Um, I'm at work atm, but I believe it was setting permissions. I will check when I get home.

Should mediabox.sh be able to be run from the Ubuntu user that I create when installing Ubuntu Server? As that didn't seem to have enough permissions to run it properly.

Also, thanks for getting back to me so quick :)

**Comment by tom472** [comment]
Yes, whatever user you have created for normal use on the server can run the mediabox.sh script.

You may now need to delete the whole mediabox directory as the permissions for the sub-directories might be messed up now.

Everything should be being done as your regular user account. 

The setting permissions part does take a few minutes because a couple containers need to be stopped, adjusted and then restarted.

So I would suggest deleting the mediabox folder and starting again from the git clone part.

Let me know.

**Comment by tom472** [comment]
I'm going to guess that no news is good news and that this is resolved.
If that is not the case and there is still an issue with this, please re-open the issue.
