### ISSUE TITLE
Deluge setup

### ISSUE THREAD

**Issue by ageisen2000** [tom472/mediabox#54]
Right now I have an external hard drive that I'd like to download / seed from. Is there an option to specify download directory with deluge?

Doesn't having Deluge automatically move files also mess with sonarr/radarr hard links? I was under the impression that everything had to stay in the same folder and the sonarr /downloads folder was supposed to point to where the torrent was downloaded to.

**Comment by tom472** [comment]
I will be adding the option to designate your download location, should be added in pretty soon. I might be out of town this weekend but I'm going to try and get it added in quickly.

The second part of your post is kind of up to your overall configuration.
I have always had my download manager move my completed files after the seed ratio has been met, that way Deluge is doing the same thing every time instead of having app x or app y handle the file moving.

Most apps generally have a setting of - let the download manager handle file moving.
Then the apps just need to know the location(s) of the "moved to" location(s).

**Comment by Switcher05** [comment]
Would there be any way to support a networked folder? I have my external drive mapped through linux just fine however I have been struggling with getting it passed to the plex docker container. I am not sure if it is either a permission or setup issue.

**Comment by tom472** [comment]
OK - asking for your download location has been added in and should be good to go.

To update just re-run the `./mediabox.sh` script.

I'll leave this thread open for a bit longer.

Thanks
