### ISSUE TITLE
Possible to add Radarr?

### ISSUE THREAD

**Issue by wibuf** [tom472/mediabox#8]
https://github.com/Radarr/Radarr

**Comment by tom472** [comment]
Yes - I have been looking into adding Radarr 
Just need a bit of spare time - there already is a known good Docker container for it so adding it in shouldn't take too long.

Since you are interested - let me ask you a question:
Would you be interested in having Radarr available alongside Couchpotato?
Or in place of Couchpotato?

Just trying to get a feel for people's thoughts. 

Thanks

**Comment by wibuf** [comment]
I've always had a bunch of issues with Couch so I would be looking to replace it completely with Radarr. There may be some people wanting Couch though so if there's a way to make it an option it may be good to include both.

**Comment by tom472** [comment]
@wibuf Sorry for the delay on this - 
I hope to be able to get on this pretty shortly.

**Comment by tom472** [comment]
Radarr has been added to Master via pull https://github.com/tom472/mediabox/pull/12

Thanks for the suggestion - Again sorry for the delay on this.
