### ISSUE TITLE
More PIA VPN Options

### ISSUE THREAD

**Issue by orbing** [tom472/mediabox#90]
I live in Australia and the options for the servers available aren't great for downloading. Would it be possible to add all configurations to the repo? 
P.S. Sorry i don't know how to add labels to issues.

**Comment by tom472** [comment]
I'll have to check into this because the DelugeVPN container needs port forwarding available. The sites to choose from are currently the ones that PIA offers for that option.

**Comment by tom472** [comment]
Here are the locations that can be used because they are the ones that PIA allows for port-forwarding. Unfortunately for technical reasons we are limited to these locations.

The following port forwarding enabled gateways:

CA Toronto
CA Montreal
CA Vancouver
Czech Republic
DE Berlin
DE Frankfurt
France
Israel
Romania
Spain
Switzerland
Sweden
