### ISSUE TITLE
Add Tdarr Docker Support

### ISSUE THREAD

**Issue by wibuf** [tom472/mediabox#93]
Tdarr is an app for file transcode automation

https://github.com/HaveAGitGat/Tdarr
https://old.reddit.com/r/PleX/comments/e73tw5/tdarr_beta_videoaudio_library_transcoderemux/

It has Nvidia GPU support so that would be nice to have as well

**Comment by archshift2** [comment]
I was able to setup Tdarr fairly easily using a docker-compose.override.yml file. This file sits alongside the docker-compose.yml file and will slipstream any additional containers into the mediabox install. Only item missing is you will have to manually add a link in the muximux file after each update or type the address/port manually to acces

[docker-compose.override.zip](https://github.com/tom472/mediabox/files/6275847/docker-compose.override.zip)

File added for reference. Had to zip because github wont allow for .yml attachment.

**Comment by tom472** [comment]
@archshift2 - Thanks for the info and the file -- I'll try and get a bit of time to have a look / test.

Thanks
--Tom

**Comment by tom472** [comment]
@archshift2 -- For the "missing part" you mention of needing to add a link in Muximux -- 
Would that be for just the web-frontend part of Tdarr?
Or would the "node(s)" need a Muximux entry too?

**Comment by archshift2** [comment]
@tom472 - its just for the WebUI.
I have been running this setup for a couple weeks and it has worked really well. Saved about 20% of disk space. The distributed node is a nice feature too. I was able to install the node on my daily PC and run transcodes overnight to assist with the load.

Muximux image for reference.
![image](https://user-images.githubusercontent.com/48061790/114079506-e5da1a80-986f-11eb-9c38-efc27c227ad9.png)

**Comment by tom472** [comment]
OK that shouldn't be to hard to account for and add in .. 
The weekend is coming - maybe I'll be able to get this added in - thanks again for the effort, info and feedback.
--Tom

**Comment by tom472** [comment]
Thanks to the awesome post and yml file from @archshift2 -- Tdarr has been added into Mediabox.
Please give it a test and see how it is working.
Thanks Again @archshift2 !!
